# Generated by Django 5.0.4 on 2024-04-13 20:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_title', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)])),
                ('usage_date', models.DateField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='владелец карты')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'карты',
                'ordering': ('-id',),
            },
        ),
    ]
